<a href="https://colab.research.google.com/github/DorotaJanosz/machine-learning-bootcamp/blob/master/supervised/02_regression/01_linear_regression_normal_equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

###Równanie normalne

In [2]:
X1 = np.array([1, 2, 3, 4, 5, 6])
Y = np.array([3000, 3250, 3500, 3750, 4000, 4250])
m = len(X1)

print(f'Lata pracy: {X1}')
print(f'Pensja: {Y}')
print(f'Liczba próbek: {m}')

Lata pracy: [1 2 3 4 5 6]
Pensja: [3000 3250 3500 3750 4000 4250]
Liczba próbek: 6


In [0]:
X1 = X1.reshape(m, 1)

In [4]:
bias = np.ones((m, 1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [5]:
X = np.append(bias, X1, axis=1) #łączy dwie tablice w jedną, stawiając je obok siebie
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [6]:
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [7]:
P = np.dot(X.T, Y)
P

array([21750., 80500.])

In [8]:
np.dot(L, P)

array([2750.,  250.])

###Regresja liniowa przy pomocy scikit-learn

In [9]:
import sklearn

from sklearn.linear_model import LinearRegression

regression = LinearRegression()
regression.fit(X1, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
print(f'Współwczynnik w0 = {regression.intercept_}')
print(f'Współczynnik w1 = {regression.coef_[0]}')

Współwczynnik w0 = 2750.0
Współczynnik w1 = 250.0
